#!/usr/bin/env ruby -KU

require 'uri'
require 'erb'
require File.expand_path(File.dirname(__FILE__) + '/helpers')

AUTHENTICATION_CHECK_URL = 'https://api.github.com/user'.freeze

def write_down_and_check!
  check_system
  case ARGV[0]
  when nil
    exec 'open', ACCESS_TOKEN_URL
  when '--help'
    $stdout.puts "Usage: #{$0} token"
    $stdout.puts
    $stdout.puts "Learn more at: https://github.com/bachue/github-notifier-for-mac"
  when String
    token = ARGV[0]
    if check(token) && write_oauth_basic_token(token)
      launchd_path = File.expand_path '~/Library/LaunchAgents/git.bachue.githubnotifier.plist'
      File.open(launchd_path, 'w') do |f|
        f << ERB.new(File.read(File.expand_path(File.dirname(__FILE__) + '/git.bachue.githubnotifier.plist.erb'))).result
      end
      system 'launchctl', 'upload', launchd_path # Ignore any error message
      $stdout.puts "launchctl load #{launchd_path}"
      exec 'launchctl', 'load', launchd_path
    else
      $stderr.puts "Failed! Please double check the access tokens on #{ACCESS_TOKEN_URL}!"
      exit 1
    end
  end
end

def write_oauth_basic_token token
  path = oauth_basic_token_path
  File.open(path, 'w') {|file| file << token }
  true
end

def check token
  uri = URI AUTHENTICATION_CHECK_URL
  response = get uri, basic_header(token)
  response.code == '200'
end

write_down_and_check!
