#!/usr/bin/env ruby -KU

require 'time'
require 'uri'
require File.expand_path(File.dirname(__FILE__) + '/helpers')

NOTIFICATION_CHECK_URL = 'https://api.github.com/notifications'.freeze

def check_notifications!
  check_system
  token = read_oauth_basic_token
  uri = URI NOTIFICATION_CHECK_URL

  uri.query = "since=#{since}" if since

  notifications = get_json uri, basic_header(token)

  notifications.each { |notification| send_notification notification, token }
  touch_timestamp
end

def read_oauth_basic_token
  if File.readable? oauth_basic_token_path
    File.read oauth_basic_token_path
  else
    $stderr.puts <<-ERROR
Failed to read #{oauth_basic_token_path}
Please apply for a personal access token on #{ACCESS_TOKEN_URL}
Run `github-notifier <token>`
    ERROR
    exit 1
  end
end

def since
  time = read_time
  iso8601(time) if time
end

def read_time
  if File.readable? timestamp_path
    str = File.read timestamp_path
    Time.at str.to_i
  end
end

def touch_timestamp
  File.open(timestamp_path, 'w') {|file| file << Time.now.to_i.to_s }
  File.chmod 0666, timestamp_path
end

def send_notification notification, token
  title = notification['repository']['full_name']
  message = notification['subject']['title']
  type = notification['subject']['type'].scan(/[A-Z][a-z]+/).join(' ')
  details_url = URI notification['subject']['url']
  details = get_json details_url, basic_header(token)
  url = details['html_url']

  `#{$terminal_notifier} -title 'Github #{type}' -subtitle #{title.inspect} -message #{message.inspect} -open #{url.inspect}`
end

check_notifications!
